### ISSUE TITLE
Cache the APK to skip Downloading APK at client

### ISSUE THREAD

**Issue by mwshubham** [theapache64/stackzy#59]
**Is your feature request related to a problem? Please describe.**
It will solve slow internet related problems

**Describe the solution you'd like**
APK should be downloaded to servers and results should be shared on clients. This will speed up the process and effective caching can help to display results with much ease.

**Comment by theapache64** [comment]
Hi @mwshubham,

Initially, I started the project with the same architecture. The problem was we needed strong servers (simultaneous decompiling takes a lot of time) with clustering to balance the load, and also these servers are pretty costly. As a mobile dev, I won't be having much time to take care of the servers. so that's why I moved with the current architecture where the decompiling will be done at the client's side. 

By the way, we've another caching mechanism inside Stackzy. Are you aware about that? 

See  https://twitter.com/theapache64/status/1380093648969195523
